openapi: 3.0.0
info:
  title: Student Management API
  description: This API allows you to manage student records.
  version: 1.0.0
servers:
  - url: http://localhost:8001
paths:
  /students:
    get:
      summary: Retrieve all students
      description: Get a list of all students currently registered.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
    post:
      summary: Create a new student
      description: Add a new student record to the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewStudent'
      responses:
        '201':
          description: Student created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
  /students/{id}:
    get:
      summary: Retrieve student by ID
      description: Get information about a specific student by their ID.
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the student to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '404':
          description: Student not found
    put:
      summary: Update student details
      description: Update the details of an existing student.
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the student to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStudent'
      responses:
        '200':
          description: Student details updated successfully
        '404':
          description: Student not found
    delete:
      summary: Delete a student
      description: Remove a student record from the system.
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the student to delete
          schema:
            type: integer
      responses:
        '200':
          description: Student deleted successfully
        '404':
          description: Student not found
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
    NewStudent:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
    UpdateStudent:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
